services:
#  dev:
#    container_name: dev
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: tail -f /dev/null # Keep the container running
#  app:
#    container_name: app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#      - postgres
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
