networks:
  my-network:
    driver: bridge

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
        - "3000:3000"
    networks:
        - my-network
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
        - my-network
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    networks:
        - my-network
    volumes:
      - ./data/db-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
